### Para crear una nueva pelicula
POST http://localhost:3333/movies
Content-Type: application/json

{
  "id": "paisfi+pajfipajfpiajnfganf0inasi0dnai0dnaw9afga",
  "name": "Hardcore Henry",
  "alternate_names": [],
  "species": "human",
  "gender": "male",
  "house": "",
  "dateOfBirth": null,
  "yearOfBirth": null,
  "wizard": false,
  "ancestry": "",
  "eyeColour": "",
  "hairColour": "",
  "wand": {
    "wood": "",
    "core": "",
    "length": null
  },
  "patronus": "",
  "hogwartsStudent": false,
  "hogwartsStaff": false,
  "actor": "Andrei Dementiev (cuerpo), Sharlto Copley (voz)",
  "alternate_actors": [],
  "alive": true,
  "image": "https://m.media-amazon.com/images/I/51e9rXvt-lL.jpg"
}

### creacion de otra pelicula
POST http://localhost:3333/movies
Content-Type: application/json

{
      "id": "akbkulaugadbga+bg+oa",
      "name": "Peter Parker",
      "alternate_names": ["Spider-Man"],
      "species": "human",
      "gender": "male",
      "house": "",
      "dateOfBirth": "1984-08-10",
      "yearOfBirth": 1984,
      "wizard": false,
      "ancestry": "unknown",
      "eyeColour": "hazel",
      "hairColour": "brown",
      "wand": {
        "wood": "",
        "core": "",
        "length": null
      },
      "patronus": "",
      "hogwartsStudent": false,
      "hogwartsStaff": false,
      "actor": "Tobey Maguire",
      "alternate_actors": [],
      "alive": true,
      "image": "https://i.ebayimg.com/thumbs/images/g/92AAAOSwaShmMs5X/s-l1200.jpg"
}
