### para recuperar toda la Api => Get
GET http://localhost:3333/movies

### para recuperar por Id
GET http://localhost:3333/9e3f7ce4-b9a7-4244-b709-dae5c1f1d4a8

### para recuperar por Genero
GET http://localhost:3333/movies?gender=female

### para recuperar por año
GET http://localhost:3333/movies?yearOfBirth=1980

### para recuperar por name 
GET http://localhost:3333/movies?name=Stewart%20Ackerley
